import json
extra = [
("30-1","R-30","Campo atrás","Un equipo controla en pista de ataque cuando un jugador con el balón tiene ambos pies y el balón totalmente en ella, o el balón ya estaba allí controlado."),
("30-2","R-30","Campo atrás","Hay campo atrás si un atacante en control es el último en tocar el balón en pista de ataque y el primero (él o un compañero) en tocarlo en pista de defensa."),
("30-3","R-30","Campo atrás","Un jugador en el aire conserva el estatus (ataque o defensa) del último pie que pisó; saltar desde ataque y caer en defensa con el balón puede ser campo atrás."),
("30-4","R-30","Campo atrás","No hay campo atrás si el balón vuelve a la defensa por un toque del rival, durante un salto entre dos, o en un rebote tras un tiro."),
("30-5","R-30","Campo atrás","Penalización: saque para el rival en su pista de ataque, desde el punto más cercano (salvo detrás del tablero)."),
("31-1","R-31","Interposición/interferencia","Un tiro empieza al soltarse el balón y termina al entrar, al verse que no entrará, al tocar el aro o al ser tocado por un jugador; en su descenso aplican las reglas de interposición."),
("31-2","R-31","Interposición/interferencia","Interposición: tocar el balón cuando baja totalmente por encima del nivel del aro en un tiro, o tras tocar el tablero estando sobre el aro."),
("31-3","R-31","Interposición/interferencia","Interferencia: tocar el balón o la canasta (aro, red, tablero) con el balón dentro o sobre el aro, o meter la mano por debajo del aro y tocarlo."),
("31-4","R-31","Interposición/interferencia","Si la comete la defensa, se conceden los puntos al ataque (2 o 3 según la zona del tiro); si la comete el ataque, no hay puntos y saque para el rival."),
("31-5","R-31","Interposición/interferencia","Una vez que el balón toca el aro, cualquiera puede tocarlo aunque esté por encima del nivel del aro: ya no es interposición."),
("31-6","R-31","Interposición/interferencia","En un tiro libre, tocar el balón en su trayectoria descendente hacia la canasta es interposición; si la comete la defensa, se concede el punto."),
("33-1","R-33","Contacto","El defensor obtiene posición legal inicial al encarar al rival con ambos pies en el suelo; luego puede moverse para mantenerla (lateral o atrás) sin extender brazos o piernas hacia el contacto."),
("33-2","R-33","Contacto","Al rival con el balón no se le debe tiempo ni distancia: debe estar listo para detenerse o cambiar cuando un defensor toma posición legal frente a él, aunque sea muy rápido."),
("33-3","R-33","Contacto","Al rival sin el balón sí se le debe tiempo y distancia (hasta un paso normal) para que pueda detenerse o cambiar de dirección."),
("33-4","R-33","Contacto","Quien salta a un punto tiene derecho a caer en el mismo lugar; el rival no puede colocarse en su trayectoria de aterrizaje después del salto."),
("33-5","R-33","Contacto","Cilindro y verticalidad: cada jugador tiene derecho al espacio vertical sobre su posición; el defensor que salta vertical dentro de su cilindro no comete falta aunque haya contacto."),
("33-6","R-33","Contacto","El semicírculo de no carga anula la falta de carga del atacante cuando el defensor tiene un pie dentro del semicírculo y el atacante llega desde fuera en penetración."),
("33-7","R-33","Contacto","Pantalla: quien la pone debe estar inmóvil y dentro de su cilindro; si la coloca fuera del campo visual del rival, debe dejarle espacio para un paso normal."),
("34-1","R-34","Falta personal","Contacto ilegal con un rival (vivo o muerto el balón) al bloquear, sujetar, empujar, cargar o impedir el avance con brazos, hombros, caderas o piernas."),
("34-2","R-34","Falta personal","Sin acción de tiro: saque para el equipo del agredido, o 2 tiros libres si el equipo está en penalización (5.ª falta de equipo)."),
("34-3","R-34","Falta personal","En acción de tiro: si la canasta entra vale y 1 tiro libre; si no entra, 2 o 3 tiros libres según la zona del intento."),
("34-4","R-34","Falta personal","Falta de control de equipo (la comete el atacante en control): nunca da tiros libres; saque para el rival."),
("35-1","R-35","Falta doble","Dos rivales se cometen falta personal el uno al otro aproximadamente al mismo tiempo."),
("35-2","R-35","Falta doble","Se registra una falta a cada uno, sin tiros libres; el juego se reanuda según quién tuviera el control, o por posesión alterna si no lo había."),
("36-1","R-36","Falta técnica","Conducta antirreglamentaria sin contacto: irrespeto a los árbitros, demoras, lenguaje ofensivo, colgarse del aro sin necesidad, etc."),
("36-2","R-36","Falta técnica","Penalización: 1 tiro libre para cualquier jugador del rival; el juego se reanuda desde donde estaba el balón, que conserva el equipo que lo tenía."),
("36-3","R-36","Falta técnica","Aviso por fingir falta (fake): el primer caso del equipo es un aviso; el segundo del mismo equipo es falta técnica."),
("36-4","R-36","Falta técnica","La técnica a un jugador cuenta como falta de jugador y de equipo; la del entrenador ('C') no cuenta como falta de equipo pero suma para su descalificación."),
("36-5","R-36","Falta técnica","Técnica de banquillo ('B'): se carga al entrenador por conducta de personas del banquillo; no cuenta como falta de jugador."),
("37-1","R-37","Antideportiva","Contacto que no es esfuerzo legítimo por el balón. Criterios: no jugar el balón, contacto excesivo, contacto innecesario para frenar el contraataque, o contacto sin opción real de jugar el balón."),
("37-2","R-37","Antideportiva","En transición, el contacto de un defensor por detrás o lateral sobre un atacante lanzado a canasta sin defensores entre él y el aro es antideportiva."),
("37-3","R-37","Antideportiva","Penalización: tiros libres (1, 2 o 3 según anotara y la zona) más posesión con saque desde la línea de saque en pista de ataque y 14 s."),
("37-4","R-37","Antideportiva","La segunda falta antideportiva del mismo jugador en el partido conlleva su descalificación."),
("38-1","R-38","Descalificante","Acción antideportiva flagrante de un jugador, sustituto, eliminado o miembro del banquillo (golpes, agresión, conducta extrema)."),
("38-2","R-38","Descalificante","El infractor es descalificado y debe abandonar el recinto; se conceden 2 tiros libres más posesión (saque desde la línea de saque en pista de ataque)."),
("39-1","R-39","Pelea","Agresión física entre dos o más rivales (puñetazos, patadas)."),
("39-2","R-39","Pelea","Los miembros del banquillo que abandonan su zona durante una pelea son descalificados, participen o no en ella."),
("39-3","R-39","Pelea","Sea cual sea el número de descalificados por dejar el banquillo, se carga una sola técnica 'B' al entrenador; las descalificantes enfrentadas se cancelan y el juego se reanuda donde estaba."),
("42-1","R-42","Situaciones especiales","Ocurren cuando, en el mismo intervalo de balón muerto tras una infracción, se producen más faltas o infracciones."),
("42-2","R-42","Situaciones especiales","Se registran todas las faltas y se aplican sus penalizaciones en el orden en que ocurrieron."),
("42-3","R-42","Situaciones especiales","Las penalizaciones iguales contra ambos equipos se cancelan entre sí; no se cancela el control del balón existente."),
("42-4","R-42","Situaciones especiales","Tras cancelar las penalizaciones iguales, el juego se reanuda como estaba: con el control que existía o por posesión alterna."),
("43-1","R-43","Tiros libres","El tirador se coloca tras la línea, dentro del semicírculo, y tiene 5 s para lanzar tras recibir el balón; el balón debe tocar el aro."),
("43-2","R-43","Tiros libres","Los jugadores de los espacios del pasillo no entran a la zona, ni los demás cruzan sus líneas, hasta que el balón sale de la mano del tirador."),
("43-3","R-43","Tiros libres","Violación solo del tirador: el tiro no vale (saque para el rival si era el último). Violación solo de un compañero: vale si entra, se repite si no. Violación solo de la defensa: vale si entra, se repite si no."),
("43-4","R-43","Tiros libres","Violación de ambos equipos a la vez en el último tiro fallado: situación de salto resuelta por posesión alterna."),
("44-1","R-44","Errores rectificables","Categoría 1: conceder tiros libres indebidos, no conceder los merecidos, fallar al anotar o anular puntos, o sancionar al jugador equivocado."),
("44-2","R-44","Errores rectificables","Plazo: solo se corrigen si se detectan antes de que el balón se vuelva vivo tras el primer balón muerto posterior a poner el reloj en marcha después del error."),
("44-3","R-44","Errores rectificables","Al corregir, los puntos legítimos se mantienen y los indebidos se anulan; las faltas registradas quedan, salvo las que dependían del error."),
("44-4","R-44","Errores rectificables","Tras la corrección, el juego se reanuda desde el punto donde se detuvo para corregir."),
("44-5","R-44","Errores rectificables","Los errores de categoría 2 (del reloj de lanzamiento) se corrigen aparte, en cuanto se detectan, mientras el balón esté muerto."),
]
data = json.load(open("src/data/obri.json"))
for n,r,a,s in extra:
    data.append({"num": n, "regla_id": r, "art": a, "resumen_propio": s})
json.dump(data, open("src/data/obri.json","w"), ensure_ascii=False, indent=1)
print("Total interpretaciones OBRI ahora:", len(data))
