import json
# (num, regla_id, art, resumen) — resúmenes originales en español de las interpretaciones OBRI 2024
E = [
("4-1","R-4","Equipos","Todo el equipamiento adicional (camisetas interiores, mangas, muñequeras, cintas y vendajes) debe ser del mismo color sólido en todo el equipo."),
("4-4","R-4","Equipos","Las cintas de cabeza tipo pañuelo (scarf) no están permitidas."),
("4-6","R-4","Equipos","Bajo el uniforme solo se admiten prendas de compresión; una camiseta normal no compresiva no se permite."),
("4-7","R-4","Equipos","Las prendas de compresión bajo el pantalón pueden ser de cualquier largo (hasta encima de la rodilla o hasta el tobillo)."),
("5-1","R-5","Lesión","Si alguien del banquillo entra a la cancha por un jugador lesionado, se considera que este recibió atención y debe ser sustituido, aunque no se le tratara."),
("5-5","R-5","Lesión","Desde el banquillo se puede asistir a un jugador (toalla, agua) sin sustituirlo, siempre que no demore la reanudación."),
("5-7","R-5","Lesión","Si el jugador cae y se levanta de inmediato (unos 15 s) sin tratamiento que demore el juego, no necesita ser sustituido."),
("5-14","R-5","Lesión","Quien sangra o no puede seguir de inmediato debe ser sustituido; si se recupera durante un tiempo muerto antes de que se llame al suplente, puede continuar."),
("5-16","R-5","Lesión","Si un titular es sustituido por lesión, el rival también puede sustituir el mismo número de jugadores."),
("7-1","R-7","Entrenador","40 min antes, el entrenador entrega la lista con números, capitán y cuerpo técnico; 10 min antes firma confirmando los datos."),
("7-2","R-7","Entrenador","Errores de número se corrigen sin sanción; si tras empezar el partido falta un nombre, ya no puede añadirse."),
("7-7","R-7","Entrenador","Si entrenador y ayudante son descalificados, el capitán actúa como entrenador-jugador."),
("8-2","R-8","Tiempo de juego","Falta cerca del fin de cuarto: los árbitros deciden si fue antes de la señal; si fue antes cuenta y se reponen los segundos, si fue después se ignora (salvo antideportiva o descalificante)."),
("8-3","R-8","Tiempo de juego","Triple en el aire al sonar la señal final: vale; una falta posterior con el tirador aún en el aire se ignora (salvo antideportiva o descalificante)."),
("9-2","R-9","Inicio/fin","La obligación de presentar 5 jugadores es solo al inicio del partido; después se puede seguir con menos."),
("9-3","R-9","Inicio/fin","Si un equipo tiene suplentes, debe jugar con 5; no se le permite reducir a 4 por 'fair play'."),
("9-5","R-9","Inicio/fin","Si juegan hacia canastas equivocadas, se corrige al detectarlo sin perjudicar a nadie; lo anotado antes sigue válido."),
("9-7","R-9","Inicio/fin","Falta del saltador antes de que el balón deje las manos del árbitro = falta en el intervalo; después = falta del primer cuarto."),
("10-1","R-10","Estado del balón","Si el defensor comete falta tras iniciar el tirador su movimiento continuo, el balón no muere y la canasta, si entra, cuenta."),
("10-3","R-10","Estado del balón","Si quien comete la falta es el atacante (falta de control de equipo), el balón muere y la canasta no cuenta."),
("12-3","R-12","Salto/posesión","Si un saltador toca el balón antes de que alcance su punto más alto en el salto inicial, es violación; saque para el rival."),
("12-16","R-12","Salto/posesión","Si el balón se encaja entre aro y tablero, es situación de salto y se aplica la posesión alterna (14 s si saca el ataque, 24 si la defensa)."),
("12-22","R-12","Salto/posesión","Hay balón retenido cuando dos rivales sujetan el balón con firmeza y ninguno puede ganarlo sin brusquedad."),
("12-24","R-12","Salto/posesión","Si el equipo con la flecha comete violación en su saque de posesión alterna, pierde ese saque y la flecha cambia."),
("12-26","R-12","Salto/posesión","Situación de salto sin tiempo en el reloj de lanzamiento y flecha a favor del ataque = violación de 24 s; balón para el rival."),
("13-1","R-13","Cómo se juega","Es violación colocar el balón entre las piernas para fingir pase o tiro, o usar deliberadamente cabeza, puño o piernas para jugarlo."),
("13-4","R-13","Cómo se juega","No se puede aumentar la altura o el alcance: levantar a un compañero para jugar el balón es violación."),
("14-1","R-14","Control del balón","El control de equipo empieza cuando un jugador sostiene o bota el balón vivo, o lo tiene a disposición para saque o tiro libre."),
("14-3","R-14","Control del balón","Si un defensor en el aire solo palmea el balón fuera, el ataque conserva su reloj; si lo controla, hay nuevo control y 24 s nuevos."),
("15-1","R-15","Acción de tiro","La acción de tiro empieza cuando el jugador comienza a mover el balón hacia arriba a la canasta."),
("15-3","R-15","Acción de tiro","En una entrada en movimiento continuo, la acción de tiro empieza cuando el balón queda en las manos tras el bote o la recepción y arranca el gesto."),
("15-5","R-15","Acción de tiro","En un tiro en suspensión, el jugador sigue en acción de tiro hasta volver con ambos pies al suelo (3 tiros si era de 3)."),
("15-8","R-15","Acción de tiro","Si tras ser objeto de falta el jugador pasa el balón, deja de estar en acción de tiro."),
("15-10","R-15","Acción de tiro","Si tras la falta el tirador anota pero comete pasos, la canasta no cuenta y se conceden 2 o 3 tiros libres."),
("16-1","R-16","Canasta y valor","El valor del tiro lo define el lugar desde donde se soltó el balón: 2 desde la zona de dos, 3 desde la de tres."),
("16-4","R-16","Canasta y valor","Si un jugador anota por error en su propia canasta, los 2 puntos se acreditan al capitán rival en cancha."),
("16-10","R-16","Canasta y valor","Una canasta directa desde un saque vale 2 aunque se suelte tras la línea de 3; solo vale 3 desde un tiro o pase jugado en cancha."),
("16-11","R-16","Canasta y valor","Con 0,3 s o más se puede hacer un tiro normal; con 0,2 o 0,1 solo vale palmeo o mate directo."),
("17-1","R-17","Saque","Durante el saque nadie salvo el sacador puede pasar parte del cuerpo sobre la línea; el defensor debe evitar tocar el balón en manos del sacador."),
("17-2","R-17","Saque","Si el defensor cruza la línea e interfiere el saque, es violación más aviso al equipo; repetirlo puede ser técnica."),
("17-4","R-17","Saque","Con 2:00 o menos en el 4.º cuarto o prórroga, el defensor no puede cruzar el cuerpo sobre la línea para interferir el saque (técnica)."),
("17-7","R-17","Saque","El sacador debe pasar el balón, no entregarlo en mano a un compañero."),
("17-12","R-17","Saque","Con 2:00 o menos en el 4.º, tras tiempo muerto el entrenador decide si el saque es desde su pista de ataque o de defensa; la decisión es final."),
("17-22","R-17","Saque","Al iniciar los cuartos (salvo el 1.º) y las prórrogas, el saque se hace desde la prolongación de la línea central, con un pie a cada lado."),
("17-31","R-17","Saque","Tras recibir el balón, el sacador no puede botarlo, dejar que toque dentro y volver a tocarlo antes que otro jugador."),
("17-37","R-17","Saque","Tras canasta o último tiro libre, el sacador detrás del fondo puede moverse lateral y hacia atrás y pasar entre compañeros, sin exceder 5 s."),
("17-50","R-17","Saque","Si el balón entra pero la canasta o el último tiro libre no es válido, se reanuda con saque desde la prolongación de la línea de tiros libres."),
("23-1","R-23","Fuera de banda","Provoca la salida quien toca el balón estando sobre o fuera de la línea."),
("23-2","R-23","Fuera de banda","Tocar con el cuerpo a un rival que tiene un pie fuera es legal: uno está fuera solo si él mismo toca fuera."),
("23-3","R-23","Fuera de banda","Si el balón toca a un rival que tiene un pie fuera, ese rival provoca la salida."),
("24-1","R-24","Regate","Lanzar deliberadamente el balón contra el tablero no cuenta como regate."),
("24-3","R-24","Regate","Tras terminar el regate, lanzar el balón al tablero y botarlo de nuevo es dobles; tocarlo sin botar para tirar o pasar es legal."),
("24-5","R-24","Regate","Tras parar legalmente, tocar el suelo con el balón al perder equilibrio o pasarlo de una mano a otra sin mover el pivote es legal."),
("24-7","R-24","Regate","Terminar el regate, lanzar el balón a la pierna del rival y recuperarlo para botar otra vez es dobles (lo tocó el balón, no el rival)."),
("24-8","R-24","Regate","Si tras el regate el balón toca a otro jugador, se puede volver a botar."),
("25-1","R-25","Pasos","Caer al suelo con el balón es legal; rodar o intentar levantarse sosteniéndolo es pasos."),
("25-3","R-25","Pasos","Tendido en el suelo se puede pasar o empezar a botar; intentar levantarse sosteniendo el balón es pasos."),
("25-4","R-25","Pasos","Tras terminar el bote o ganar el control, no se puede tocar el suelo consecutivamente con el mismo pie o con ambos."),
("26-1","R-26","Tres segundos","Salir por el fondo para evitar los 3 segundos y volver a entrar a la zona es violación."),
("26-4","R-26","Tres segundos","Si el jugador suelta un tiro estando en la zona y captura su propio rebote, no hay 3 segundos (terminó el control y empezó otro)."),
("26-5","R-26","Tres segundos","No hay 3 segundos si el reloj de juego aún no corre (por ejemplo con el sacador sosteniendo el balón)."),
("27-1","R-27","Cinco segundos","El jugador estrechamente marcado debe pasar, tirar o botar en 5 segundos."),
("27-2","R-27","Cinco segundos","Que se le escape y recupere el balón no cuenta como bote: la cuenta de 5 segundos sigue corriendo."),
("28-3","R-28","Ocho segundos","El balón pasa a pista de ataque cuando ambos pies del botador y el balón están totalmente en ella."),
("28-1","R-28","Ocho segundos","Si tras un balón retenido el saque de posesión alterna vuelve al equipo que controlaba en su defensa, continúa la cuenta de 8 segundos."),
("28-9","R-28","Ocho segundos","Si el juego se detiene por causa ajena a los equipos y reanudar con 8 s nuevos perjudicaría al rival, la cuenta de 8 segundos continúa."),
("28-13","R-28","Ocho segundos","El control de equipo termina cuando el balón sale de las manos en un tiro; un triple desde la defensa justo al acabar los 8 s es legal."),
("29-1","R-29","Reloj de 24","Tiro en el aire al sonar el reloj: si entra vale; si toca aro y rebota sigue (14 s si recupera el mismo equipo, 24 si el rival); si falla el aro hay violación salvo que el rival gane el control de inmediato."),
("29-6","R-29","Reloj de 24","Si la falta al tirador ocurrió antes de expirar el reloj (o el balón ya iba en el aire), no hay violación de 24 y la canasta cuenta; si la falta fue después con el balón aún en las manos, sí hay violación."),
]
out = [{"num": n, "regla_id": r, "art": a, "resumen_propio": s} for (n, r, a, s) in E]
json.dump(out, open("src/data/obri.json", "w"), ensure_ascii=False, indent=1)
print("Interpretaciones OBRI cargadas:", len(out))
